import random

# Kelime ve Türkçe anlamlarını doğrudan tanımla
kelimeler = [
    "absorb;içine çekmek",
    "abundant;bol",
    "abuse;kötüye kullanmak",
    "accelerate;hızlandırmak",
    "accept;kabul etmek",
    "access;erişmek",
    "accomplish;başarmak",
    "accuracy;doğruluk",
    "achieve;başarmak",
    "adopt;uyum sağlamak",
    "adore;çok sevmek",
    "advance;terfi",
    "affect;etkilemek",
    "aid;yardım etmek",
    "agree;kabul etmek",
    "alter;değiştirmek",
    "amaze;şaşırtmak",
    "analyze;analiz etmek",
    "announce;duyurmak",
    "apologize;özür dilemek",
    "Apolling;korkunç",
    "Appetizer;iştah açıcı Appetizer: meze Unappetizing: iştah açıcı olmayan Unappetizing: iştahsız",
    "*Appropriately;uygun olarak",
    "Approve of;onaylamak",
    "Arrange;düzenlemek",
    "Artefact;insan eliyle yapılmış sanat",
    "Arise(Arouse-V2);uyandırmak",
    "Arrive;varmak",
    "Ascend;yukarı çıkmak",
    "Ask for;ricada bulunmak",
    "Aspect;görünüm",
    "Aspire;şiddetle arzu etmek"
    "Assert;ileri sürmek iddia etmek",
    "Assess;değer biçmek",
    "Assign;atamak",
    "Assist somebody in something;birine bir konuda yardım etmek",
    "Associate;ilgili olmak",
    "Assure;birine teminat vermek",
    "Astonishment;şaşırtmak",
    "Attach;iliştirmek",
    "Attack;saldırmak",
    "Attain;elde etmek",
    "Attend;iştirak etmek",
    "Attribute;bağlanmak"
    "Auditorium;dinlenme/izleme salonu",
    "Available;mevcut",
    "Avert;önlemek",
    "Attempt;teşebbüs etmek",
    "Avoidable;kaçınılabilir",
    "Award;ödül"
    "Battle;savaş",
    "Barren;kurak",
    "Basic;temel",
    "Ban;yasaklamak",
    "Bear;tahammül etmek",
    "Behave;davranmak"
    "Believe;inanmak",
    "Belongings;birinin kişisel eşyaları",
    "Benefit;yarar sağlamak Profit: kar Beneficial: faydalı Profitable: karlı Capitalise on: yararlanmak",
    "Betrayal;ihanet Betrayed: ihanete uğramış",
    "Beverage-Beverage;içecek Sip: yudumlamak",
    "Bitingly satirical;aşırı alaycı"
    "Bizarre;tuhaf",
    "Blame(for);suçlamak",
    "Book;yer ayırtmak",
    "Boost;arttırmak",
    "Branch;dal",
    "Break out;ortaya çıkmak"
    "Bribery;rüşvet offer bribes: rüşvet teklif etmek",
    "Brief;kısa",
    "Bring about;neden olmak",
    "Broadcast-Broadcast;radyo TV",
    "Build;inşa etmek",
    "Burden;yük"
    "Burial;mezar",
    "Calamity;felaket",
    "Calculator;hesap makinesi",
    "Call for;talep etmek",
    "Callous;duygusuz Callousness: duygusuzluk Pride: gurur",
    "Calm;sakin"
    "Cancel;iptal etmek",
    "Captivating;büyüleyici",
    "Captive;tutsak esir",
    "Capture;yakalamak",
    "Careless;dikkatsiz",
    "Cause;sebep olmak"
    "Casually;günlük",
    "Caution;uyarı",
    "Cease;sona erdirmek",
    "Celebration;kutlama",
    "Celebrity;ünlü",
    "Census;nüfus sayımı"
    "Charge (with);-ile yargılamak",
    "Circulate;dolaşmak",
    "Cite;örneklemek",
    "Citizen;vatandaş",
    "Clarify;açıklamak",
    "Claim;iddia etmek"
    "Closed;kapalı Sealed: kapalı",
    "Coastal;kıyı",
    "Cognitive;bilişsel",
    "Coincide with;aynı tenseda denk gelmek/tesadüf etmek",
    "Collaboration;işbirliği",
    "College;iş arkadaşı"
    "Collide with;çarpışmak",
    "Commence;başlamak",
    "Comment on;yorum yapmak",
    "Commercial;ticari",
    "Commuter;ev ile iş arasında mekik dokuyan gidip gelen.",
    "Companion;dost arkadaş"
    "Compel;zorlamak",
    "Compete;rekabet etmek",
    "Competence;yeterlilik Competent: ehil Incompetent: beceriksiz",
    "Compile;derlemek bir araya getirmek",
    "Complain to somebody about something;şikayet etmek Grievance: şikayet",
    "Completely;tamamen"
    "Comply(with);-e uymak",
    "Compose;oluşturmak",
    "Compound;birleştirmek",
    "Comprise;içermek",
    "Compute;hesap yapmak",
    "Conceal;gizlemek"
    "Concept;kavram",
    "Concile(reconcile);uzlaştırmak",
    "Conclude;sonuç çıkarmak",
    "Concern(about);endişe",
    "Condition;durum",
    "Confess;itiraf etmek"
    "Confident (of);emin",
    "Conform to;uymak",
    "Confuse;karıştırmak",
    "Consequence;sonuç",
    "Conserve;korumak",
    "Considerable;large ölçüde"
    "Considerately;düşünceli/nazik bir şekilde",
    "Consideration;göz önünde bulundurma/düşünme",
    "Consistency;tutarlılık",
    "Consist of;ibaret olmak",
    "Constitute;oluşturmak",
    "Constrain;zorlamak"
    "Construct;inşa etmek",
    "Consult;danışmak",
    "Consume;tüketmek",
    "Contact with;birisi ile kontak/temas kurmak",
    "Contain;içermek",
    "Contemporary;çağdaş"
    "Context;bağlam",
    "Content with;-den memnun",
    "Contest;yarışma",
    "Contient;kıta Contiguous: bitişik",
    "Contradict;çelişmek",
    "Contribute to;katkıda bulunmak"
    "Controversial;tartışmalı",
    "Conveniently;rahatlıkla Convenient: uygun",
    "Conventional;geleneksel",
    "Convert into;dönüşmek",
    "Convict;mahkum",
    "Convince;inandırmak"
    "Correctly;doğru bir şekilde",
    "Correspond to;bir şeyle uyumak",
    "Cost;maliyet costly: pahalı",
    "Counterpart;karşılığı",
    "Couple;çift Paired: çifte",
    "Cover;kaplamak"
    "Cramped;hijyenik olmayan",
    "Crave;can atmak Craved: arzulu Craving: özlem Cravings: istek Craven: korkak",
    "Create;yaratmak",
    "Credibly;inanılır bir şekilde",
    "Criminal;ciddi bir suç/cürüm işlemiş",
    "Crippled;felçli",
    "Cross out;üstünü çizmek",
    "Cultivate;tarım yapmak",
    "Curb;azaltmak",
    "Cure;tedavi",
    "Currency;döviz",
    "Curve;eğim",
    "Custom;gelenek",
    "Date back to;o tarihe dayanmak",
    "Debate;tartışmak",
    "Debt;borç",
    "Debut;çıkış Debuted: çıkış yaptı",
    "Deceit;kandırmak",
    "Decipher;şifresini çözmek",
    "Declare;ilan etmek",
    "Decree;genelge yayınlamak",
    "Dedicate (to);kendini adamak",
    "Deduce;sonuç çıkarmak",
    "Deepen;derinleştirmek",
    "Defeat;yenmek",
    "Defect;bozukluk",
    "Defend;savunmak",
    "Define;tanımlamak",
    "Degeneration;yozlaşma",
    "Delay;geciktirmek",
    "Delightful;zevkli",
    "Demolish;yıkmak",
    "Depend;bağlı olmak",
    "Deposition;tortu",
    "Derive from;çıkarmak",
    "Descend;soyundan gelmek",
    "Desert;çöl",
    "Deserve;hak etmek –to V1 Served: servis Service: hizmet",
    "Design;plan çizmek",
    "Destination;hedef",
    "Destiny;kader",
    "Destroy;yıkmak",
    "Detain;alıkoymak",
    "Detect;meydana çıkarmak",
    "Deter (someone) from;caydırmak",
    "Deteriorate;kötüleşmek",
    "Devastate;mahvetmek",
    "Devise;planlamak",
    "Devote;adamak",
    "Diagnose as;teşhis etmek",
    "Differ;farklılık göstermek",
    "Direct;yönlendirmek",
    "Digest;sindirmek",
    "Differentiate;ayırmak",
    "Diminish;azalmak",
    "Disappearance;ortadan/gözden kaybolmak",
    "Disappoint;hayal kırıklığına uğramak",
    "Disclose;açığa çıkarmak",
    "Discover;keşfetmek",
    "Discuss about;tartışmak",
    "Disease;hastalık",
    "Dismiss;kovmak",
    "Dispatch;sevk etmek",
    "Display;göstermek",
    "Displeased;hoşnut kalmamış",
    "Dispose of;başından atmak",
    "Disqualify;diskalifiye etmek",
    "Distinct;farklı",
    "Distribute;dağıtmak",
    "Docile(sosyal);uysal",
    "Dominate;egemen/baskın olmak",
    "Donate;bağış yapmak",
    "Drug addict;eroin bağımlısı Drug Dealer: eroin ticareti yapan kişi Dealt: dağıtılan",
    "Dustbin;çöp kutusu",
    "Earth;deprem",
    "Edit;bir kitabı basılabilir hale getirmek",
    "Educate;eğitmek",
    "Effect;etki",
    "Elect;seçmek",
    "Eliminate;elemek",
    "Embarrass;utandırmak",
    "Embody;somutlaştırmak",
    "Emerge;ortaya çıkmak",
    "Emit;yaymak",
    "Emphasize;vurgulamak",
    "Emulate;taklit etmek",
    "Enable;olanaklı kılmak",
    "Enclose;çevresini sarmak",
    "Encounter;karşılaşmak",
    "Encourage;cesaretlendirmek",
    "Endow;bağışlamak",
    "Endure;dayanmak",
    "Engage;meşgul olmak",
    "Enhance;güçlendirmek",
    "Enlarge;büyütmek",
    "Enquire;sormak",
    "Enslave;köleleştirmek",
    "Ensure;birini temin etmek/emin kılmak",
    "Entail;gerektirmek",
    "Entertain;eğlendirmek",
    "Entirely;tamamen",
    "Entrance;giriş",
    "Environmental;çevresel",
    "Envy;kıskanmak",
    "Epic;destan",
    "Erode;aşınmak",
    "Equal;eşit",
    "Equip;donatmak",
    "Erupt;patlamak",
    "Establish;kurmak",
    "Estimate;tahmini bir şey/rakam söylemek",
    "Eternal;kalıcı",
    "Evaluate;değerlendirmek",
    "Event;olay",
    "Evidently;besbelli",
    "Exaggerated;abartılı",
    "Execute;yerine getirmek",
    "Excavate;kazı yapmak",
    "Exceed;aşmak",
    "Excessive;aşırı",
    "Exchange;takas etmek",
    "Exclude;çıkarmak",
    "Exclusive to;herkese açık olmayan",
    "Exclusively;sadece",
    "Excursion;keşif gezisi",
    "Exhibit;sergilemek",
    "Exist;var olmak",
    "Expand;genişlemek",
    "Expand;harcamak Expanded: harcanan",
    "Expect;ummak",
    "Expedite;hızlandırmak",
    "Expense;masraf",
    "Expel;kovmak",
    "Expire;son kullanma tarihi gelmek",
    "Explode;patlamak",
    "Exploit;patlatmak",
    "Explore;keşfetmek",
    "Export;ihraç etmek",
    "Extend;uzatmak",
    "Extract;elde etmek",
    "Facilitate;kolaylaştırmak",
    "Fade;solmak",
    "Failure;başarısızlık",
    "Fairly;oldukça",
    "Falsify;tahrif etmek",
    "Familiar(with);aşina",
    "Famish;aç kalmak",
    "Fatal;ölümcül",
    "Favourable;olumlu",
    "Fearful for;-için korkan/endişelenen",
    "Fertilize;gübrelemek",
    "Fetch;gidip getirmek",
    "Fill;doldurmak",
    "Field;alan",
    "Finance;finanse etmek",
    "Firework;havai fişek",
    "Fit;sağlıklı",
    "Flatmate;ev arkadaşı",
    "Flee;kaçmak",
    "Flow;suda yüzmek akmak",
    "Fluctuate;dalgalanmak",
    "Focus on;odaklanmak",
    "Forbid;yasaklamak",
    "Force;zorlamak",
    "Forecast;önceden tahmin etmek",
    "Forge;taklidini yapmak",
    "Former;önceki",
    "Formulate;formülleştirmek",
    "Forthcoming;gelecek",
    "Fortify;takviye etmek",
    "Fracture;kırılmak",
    "Frame-Framework;çerçeve",
    "Frighten;korkutmak",
    "Freed;serbest kalmış",
    "Fundamental;esas",
    "Funeral;cenaze töreni",
    "Fussy;aşırı titiz",
    "Gain;elde etmek",
    "Gender;cinsiyet",
    "Genre(janr);tür çeşit nevi",
    "Get rid of;başından atmak",
    "Giant;dev",
    "Give up;vazgeçmek",
    "Glance;bakış",
    "Globe;küre",
    "Gloom;karanlık",
    "Glorify;yüceltmek",
    "Goal;hedef",
    "Govern;yönetmek",
    "Grab;kopmak",
    "Gradually;yavaş yavaş",
    "Gratify;memnun etmek",
    "Grant;vermek",
    "Grave;mezarlık",
    "Tired of;yorulmak",
    "Guide;rehber",
    "Halt;durdurmak",
    "Handle;ele almak",
    "Harass;taciz etmek",
    "Hardship;zorluk",
    "Harness;tesisat",
    "Harmful;zararlı",
    "Hasten;acele etmek",
    "Havoc;hasar",
    "Hazard;tehlike",
    "Hesitate;tereddüt",
    "Highly;oldukça epey",
    "Hinder;engellemek",
    "Hitchhiker;otostopçu",
    "Hold(Held V2);tutmak",
    "Hopefully;inşallah",
    "Horrible;korkunç",
    "Hospitable;misafirperver",
    "Huge;iri",
    "Humiliate;aşağılamak",
    "Hunter;avcı",
    "Hurricane;kasırga",
    "Iceberg;buzdağı",
    "Identify;teşhis etmek",
    "Idle;tembel",
    "Ignore;görmezden gelmek",
    "Illicit;yasadışı",
    "Illusion;hayal",
    "Illustrate;örneklemek",
    "Imagine;hayal etmek",
    "İmitate;taklit etmek",
    "İmmobilize(immobilayzr);hareketsiz/sabit kılmak Fixation: sabitleme 		Anchored: demirlemek",
    "İmmune;bağıchoice immune system: bağıchoicelık sistemi",
    "Impact;çarpmak",
    "İmplement;uygulamak",
    "Implicate;bulaştırmak",
    "İmply(implay);ima etmek",
    "İmpose;zorla kabul ettirmek",
    "İmpress;etkilemek",
    "İmprisonment;hapse atmak",
    "Improve;geliştirmek",
    "Inaudible;duyulamaz",
    "Incapable of;kabiliyetsiz",
    "Incapacitate;yetersiz bırakmak",
    "Incline;eğmek",
    "Include;dahil etmek",
    "Income;gelir",
    "Incorporate into;dahil etmek",
    "Incredible;inanılmaz",
    "Indicate;belirtmek",
    "Indifference to;kayıtsız",
    "Indispen;vazgeçilmez indispensable: olmazsa olmaz Dispensable: vazgeçilebilir",
    "Individual;bireysel individually: bireysel olarak individuality: bireysellik",
    "Induce;indüklemek",
    "Inevitable;kaçınılmaz",
    "Infant;bebek infancy: bebeklik Still in its infancy: henüz emekleme aşamasında",
    "Infer;anlamak",
    "Infest;kaplamak",
    "Inflate;şişirmek inflammation: iltihaplanma inflation-inflation: şişirme",
    "Inherit;mirasa konmak",
    "Inhibit;engellemek",
    "Initially;başlangıçta",
    "Injured;yaralamak",
    "Injustice;eşitsizlik",
    "Innovate;yeni bir şey icat etmek",
    "Inquire;sormak",
    "Insist(on);ısrar etmek",
    "Inspect;incelemek",
    "Inspire;ilham vermek inspired: ilham veren",
    "Instantaneously;anlık",
    "Institute;kurmak",
    "Instruct;eğitim",
    "Insulate;yalıtmak",
    "Integrate;birleştirmek",
    "Intensify;yoğunlaşmak",
    "Intention(intention);niyet Unintended-Unwelcome: istenmeyen Malicious: kötü niyetli",
    "Intentional;kasıtlı",
    "Interaction(with);etkileşim interactive: etkileşimli",
    "Interfere;karışmak",
    "Interpretation;yorum",
    "Interrogate;sorgula çekmek"
    "Interweave;birbirine geçirmek Interweaving: iç içe geçmiş Weave: örgü",
    "Intricate;karmachoice",
    "Invade;istila etmek",
    "Invaluable;paha biçilmez",
    "Invent;icat etmek",
    "Invenst(in);para yatırım yapmak investment: yatırım",
    "Investigate;araştırmak",
    "İrreparable;onarılamaz",
    "Isolate;izole etmek",
    "Jeopardize;tehlikeye atmak",
    "Join(in);katılmak",
    "Kidnapper;adam",
    "Knock;vurmak",
    "Knowledge;bilgi",
    "Label;etiketlemek",
    "Latter;sonraki x farmer: önceki",
    "Lawyer;avukat",
    "Lease;kiralamak",
    "Legend;efsane",
    "Legislate;yasa koymak Legislation: mevzuat",
    "Leisure;boş vakit",
    "Lessen;azaltmak",
    "Likewise;buna benzer şekilde",
    "Linguist;dilbilimci",
    "Listless;yorgun",
    "Literacy;okuryazarlık Literacy rate: okuryazarlık oranı Literate: okuryazar Literature: edebiyat",
    "Litter;çöp",
    "Loathe(loof);nefret etmek",
    "Locate;yerleştirmek",
    "Location;mevki",
    "Loose;gevşetmek",
    "Lovely;sevecen sevimli",
    "Luggage(lagiç);bagaj",
    "Magical(mecikıl);sihirli",
    "Magnify;büyütmek Magnitude: largelük",
    "Maintain;korumak",
    "Make a decision;karar vermek",
    "Make up;oluşturmak",
    "Manhood;erkeklik",
    "Manipulate;elinde oynatmak",
    "Manner;biçim",
    "Manufacture;fabrikada üretmek",
    "March;ilerleme",
    "Massacre(messe=r);soykırım",
    "Matter;mesele",
    "Mastermind;tasarlamak",
    "Masterpiece;şaheser",
    "Mature(maçu);olgun",
    "Medium;araç",
    "Memorial;anıt",
    "Memory;hafıza",
    "Merge;birleştirmek",
    "Migrate;göç",
    "Miraculously;mucizevi bir şekilde Prodigy: mucize",
    "Misbehave;terbiyesizlik yapmak",
    "Mischief;yaramazlık",
    "Misunderstanding;yanlış anlaşılma",
    "Mix up;aklını karıştırmak",
    "Mockat;dalga geçmek",
    "Modify;değiştirmek",
    "Mood;ruh hali",
    "Mortality;ölüm oranı",
    "Mourning;yas",
    "Multinational;çok uluslu",
    "Municipality;belediye",
    "Mystery;gizem",
    "Narrowly;dar bir şekilde Narrow: dar",
    "Nasty;kötü",
    "Native to;yöreye has/özgü",
    "Necessary;gerekli",
    "Neglect;ihmal etmek",
    "Negotiate;görüşmek",
    "Nervous;gergin",
    "Neutrality(nötraliti);tarafsızlık",
    "Nominate;aday göstermek Applicant-Nominee: aday Candidate: aday",
    "Notably;özellikle",
    "Obese;şişman obez",
    "Obey;uymak",
    "Objection;itiraz",
    "Obligation;yükümlülük",
    "Observe;gözlemlemek Observation: gözlem Observational: gözlemsel Observed: gözlemlenen",
    "Obsession;takıntı",
    "Obsolete;modası geçmiş",
    "Obtain;elde etmek",
    "Occasional;ara sıra",
    "Occur;meydana gelmek",
    "Odour-Scent;koku",
    "Officially;resmen",
    "Operate;işletmek",
    "Opportunity;fırsat opportunist: fırsatçı Opportunities: fırsatlar",
    "Opposition;karşıtlık",
    "Ordinary;sıradan",
    "Organize;planlamak",
    "Originally;ilk başta",
    "Orphan;yetim bırakmak",
    "Outfit;kıyafet Outer: dış Outermost: en dıştaki Robe: elbise Garment: giysi",
    "Author;yazar",
    "Own;sahip olmak",
    "Overcome;aşmak",
    "Pass;geçmek",
    "Partially;kısmen",
    "Participate in;katılmak",
    "Particular;özel",
    "Passenger;toplu taşıt yolcusu",
    "Passionately;ihtirasla",
    "Path;yol Bend: viraj",
    "Patiently;sabırla",
    "Pavement;kaldırım",
    "Peace and quiet;huzur ve sükûnet",
    "Peak;doruk",
    "Peanut;fıstık",
    "Peculiar;tuhaf",
    "Pedestrian;yaya",
    "Penalize;ceza vermek",
    "Perceive;algılamak",
    "Perform;yapmak",
    "Permanent;kalıcı Permanently: kalıcı olarak",
    "Permission;izin",
    "Persevering;sebatkar",
    "Persist(in);ısrar etmek",
    "Persuade;ikna etmek",
    "Pessimism;kötümserlik",
    "Phenomenon;fenomen",
    "Pioneer;öncü",
    "Placement;yerleştirme",
    "Poem;şiir Poetry: şiir",
    "Policy;tutum kural",
    "Polio-Poliomyelitis;çocuk felci Paralyze: felç etmek",
    "Portrayal-Portrayed;tasvir Portrait: tasvir etmek",
    "Pose;ortaya çıkarmak",
    "Possess;sahip olmak",
    "Practitioner;pratisyen Practitioners: uygulayıcılar Viable: uygulanabilir Via: aracılığıyla",
    "Praise;övmek",
    "Precaution;önlem Cautious: dikkatli Cautiously: dikkatli bir şekilde",
    "Precede;-den önce gelmek Precedence: öncelik Precedented: emsal Unprecedented: benzeri görülmemiş Precedent: emsal",
    "Predict;tahminde bulunmak",
    "Prefer;tercih etmek Refers to: anlamına gelir",
    "Prejudice;önyargı",
    "Preliminary;başlıca",
    "Prescription-Prescribed;reçete Prescription: tarif Inscription: açıklama Scription: yazı Over Prescription: fazla reçete Prescriptive: kuralcı",
    "Preserve;korumak",
    "Pressure;baskı",
    "Prevalence;yaygınlık Prevalent: yaygın",
    "Prevent;engel olmak",
    "Previously;önceden",
    "Prior(to);-den önce",
    "Prison;hapishane",
    "Probability;olasılık",
    "Process;bir malzemeyi işlemek",
    "Produce;üretmek",
    "Profit;yarar sağlamak",
    "Prohibit;yasak",
    "Prolong;uzatmak",
    "Progress;ilerleme",
    "Prompt;nakit",
    "Properly;uygun bir şekilde",
    "Property;mal",
    "Proportion;oran",
    "Prosper;gelişmek",
    "Protect;korumak",
    "Prove;kanıtlamak",
    "Provoke;kışkırtmak",
    "Purchase;satın almak",
    "Purpose;amaç",
    "Pursue;izlemek",
    "Push;itmek X Pull: çekmek",
    "Put forth;öne sürmek",
    "Queue;sıra",
    "Raid;yasadışı işlere yapılan baskın",
    "Raise;artırmak",
    "Rate;oran",
    "Recall;hatırlamak",
    "Reccive;almak",
    "Reckless;dikkatsiz",
    "Recommendation;tavsiye",
    "Reduce;azaltmak",
    "Refreshing;canlandırıcı",
    "Refugee;mülteci",
    "Refund;parayı iade etmek",
    "Regional;bölgesel",
    "Regularly;düzenli bir şekilde",
    "Rehearse;prova yapmak Rehearsal: prova",
    "Reject;red etmek",
    "Release;serbest bırakmak",
    "Relief-Relieve;rahatlama",
    "Religion-Religious;din Priest: rahip Church: kilise Gospel: müjde",
    "Relocate;yerini değiştirmek",
    "Reluctant;gönülsüz",
    "Remain;kalmak",
    "Remembrance;anma",
    "Reminiscent of;andıran",
    "Renewable;yenilenebilir Novel: yeni"
    "Repeatedly;defalarca",
    "Repetitive;monoton",
    "Replenish;doldurmak Replenished: yenilenmiş",
    "Replica;aslına çok benzeyen kopya Replicate: tekrarlamak",
    "Republic;cumhuriyet",
    "Repute;itibar"
    "Request;rica etmek",
    "Require;gerektirmek",
    "Resentful;alıngan",
    "Reside;ikamet etmek",
    "Sedentary;belli bir bölgede oturanlar; sabit",
    "Resign from;-den istifade etmek ,Resignation: istifa"
    "Resilie;esnek Resilient: esnek",
    "Resist;direnmek",
    "Response;karşılık",
    "Restlessness-Unrest;huzursuzluk",
    "Restore;geri getirmek",
    "Result;sonuç",
    "Resume;yeniden başlamak",
    "Retail;perakende Retailer: perakendeci",
    "Retreat;geri çekilmek Tread: ayak basma",
    "Reveal;ortaya çıkarmak",
    "Revenge;intikam",
    "Rightfully;haklı ola,rak"
    "Rise;ortaya çıkmak",
    "Rob somebody of something;birini soymak Robbery: soygun Burgler: hırsız",
    "Robust;güçlü",
    "Rough-Rough;kabaca",
    "Sacrifice(to);adamak",
    "Satisfaction;tatmin",
    "Savage;vahşi",
    "Scarce;seyrek",
    "Scatter;saçmak",
    "Sceptical-Sceptic;şüpheci",
    "Scholarly;bilimsel Scholars: bilim adamları",
    "Sculpture;heykel",
    "Seasonal;mevsimine uygun Centenarians: asırlık",
    "Secure;güvenli",
    "Seminal;ufuk açıcı",
    "Sentimental;duygusal",
    "Session;toplantının her bir oturumu",
    "Settle;yerleşmek",
    "Sever;kesmek",
    "Shortcoming;kusur",
    "Shorten;kısaltmak",
    "Show off;hava atmak",
    "Silent;sessiz",
    "Simulate;taklit etmek"
    "Situate;konuşlandırmak",
    "Skill;beceri",
    "Slave;esir",
    "Slavery;kölelik",
    "Slight;hafif",
    "Slip;kaymak",
    "*Sociable;sıcakkanlı",
    "Society;toplum Community: toplum Cluster: küme Civilisation: medeniyet",
    "Solely;yalnızca",
    "Soothing;yatıştırıcı",
    "Sour;ekşi",
    "Sparse;seyrek X Densely: yoğun Thick: kalın Volume: hacim",
    "Specify;belirlemek Special-Specific: özel Species: türler",
    "Spectacular;görkemli",
    "Spectacles;gözlük",
    "Spend;harcamak",
    "Sperse;dağınık Disperse: yaymak",
    "Spiritual;manevi"
    "*Spoiled;şımarık",
    "Spouse;eş",
    "Sprint;sürat koşusu Sprinter: kısa mesafeli koşusu Sprinting: koşmak Race: yarış",
    "Spur;mahmuz",
    "Stability;istikrar",
    "Staff;personel",
    "Stake;tehlike",
    "Statue;heykel",
    "Steadily;sabit bir şekilde",
    "Steal;çalmak",
    "Stem;ağaç gövdesi stem from:-den kaynaklanmak",
    "Store;depo"
    "Storm;fırtına blizzard: kar fırtınası",
    "Stanger;yabancı",
    "Satisfy;tatmin etmek",
    "Strict;sıkı",
    "String;ip",
    "Structure;planl,amak"
    "Submit;sunmak",
    "Submission;teslim",
    "Substantial;çok önemli",
    "Substitute;yerine geçmek Substitutes: yedekler Substituted: değiştirilmiş Substitution: ikame Subspecies: alt türler Subcultural: alt kültür Sub: alt",
    "Succeed;başarılı olmak",
    "Sue;dava açmak"
    "Sufficiently;yeterince",
    "Suffrage;oy hakkı",
    "Suggestion;öneri",
    "Suit;yakışmak",
    "Support;desteklemek",
    "Surpass;aşmak",
    "Surrender;teslim olmak",
    "Susceptible;duyarlı",
    "Suspend;askıda",
    "Suspicion;şüphe",
    "Sustainable;sürdürülebilir Sustain: güç vermek",
    "Symptom;belirti",
    "Tame;evcil hayvan",
    "Temple;tapınak",
    "Tenderness;şefkat",
    "Territory;bölge",
    "The rest of;-nın geri kalanı",
    "Thoughtless;düşüncesiz"
    "Thrill;heyecan Thrilling: heyecan verici Thrilled: heyecanlı",
    "Thrive;gelişmek",
    "Throughout;boyunca",
    "Throw;atmak",
    "Thunder storm;yıldırımlı fırtına",
    "Toe;ayak parmağı Limbs: uzuvlar Thumb: başparmak Fist: yumruk Muscle: kas Mout: ağız Tissue-Texture: doku Gland: salgı bezi"
    "Tomb;mezar",
    "Trace;iz",
    "Traditional;geleneksel",
    "Trail;iz",
    "Trait;özellik",
    "Trash;çöp",
    "Treasure;hazine",
    "Trick;hile",
    "Unattended;sahipsiz",
    "Unbearable;katlanılmaz",
    "Uncultured;kültürsüz",
    "Undermine;zayıflatmak",
    "Unfortunate;talihsiz",
    "Universal;evrensel Microcosm: small evren",
    "Unlimited;sınırsız",
    "Unreliable;güvenilmez",
    "Untimely;vakitsiz",
    "Unusual;sıradışı",
    "Unveil;ortaya çıkarmak",
    "Upheaval;ayaklanma",
    "Upset;bozmak",
    "Urgent;acil",
    "Utilisation;kullanım Utilise: yararlanmak",
    "Vacation;tatil",
    "Vaccine;aşı Vaccination: aşılama",
    "Valley;vadi",
    "Varied;değişik",
    "Variety;değişiklik",
    "Vast;largelük",
    "Vessel;gemi",
    "Vet;veteriner",
    "Victim;kurban",
    "Victory;zafer",
    "Vigilant;uyanık",
    "Vigorously;gayretli",
    "Violent;şiddetli"
    "Virtually;sanal olarak",
    "Visibly;görülebilir biçimde",
    "Vividly;açık biçimde",
    "Vocation;meslek",
    "Volunteer;gönüllü",
    "Voyage;deniz yolculuğu"
    "Vulnerable;savunmasız",
    "Wage;maaş",
    "Waste;israf etmek",
    "Wear;takınmak",
    "Welfare;refah",
    "Wholly;tamamen"
    "Widely;geniş çapta",
    "Widow;kadın dul widower: erkek dul",
    "Wind;rüzgar",
    "Withdrawn;içine kapanık",
    "Worthless;değersiz",
    "Youthful;genç",
]

yanlis_kelime_listesi = [





]

girdi = input(str("""
Lütfen Mod seçiniz!!

1: Rastgele kelime quizi 
2: 50'lik grup yöntemi ile ezberlemek 

SEÇİLEN MOD: 
"""))


if girdi == "1":
    toplam_grup = len(kelimeler) // 50

    try:
        grup_sayisi = int(
            input(f"Hangi 50'lik satır grubundan kelime sormak istersiniz? (1 - {toplam_grup} arası bir sayı girin): "))

        if grup_sayisi > 0 and grup_sayisi <= toplam_grup:
            baslangic_index = (grup_sayisi - 1) * 50
            secilen_50lik_grup = kelimeler[baslangic_index:baslangic_index + 50]
            random.shuffle(secilen_50lik_grup)

            for rastgele_kelime in secilen_50lik_grup:
                ingilizce_kelime, turkce_anlam = rastgele_kelime.split(";")
                cevap = input(f"{ingilizce_kelime.strip()} kelimesinin Türkçe karşılığı nedir?: ")

                if cevap.strip().lower() == turkce_anlam.strip().lower():
                    print("Doğru!")
                else:
                    print(f"Yanlış! Doğru cevap: {turkce_anlam.strip()}.")
                    yanlis_kelime_listesi.append(f"{ingilizce_kelime.strip()};{turkce_anlam.strip()}")

            print(f"Son gösterilen grup: {grup_sayisi}.")

        else:
            print(f"Lütfen 1 ile {toplam_grup} arasında bir sayı girin.")

    except ValueError:
        print("Lütfen geçerli bir sayı giriniz.")
    except Exception as e:
        print(f"Bir hata oluştu: {e}")


elif girdi == "2":
    toplam_grup = len(kelimeler) // 50

    try:
        grup_sayisi = int(
            input(f"Hangi 50'lik satır grubunu görmek istersiniz? (1 - {toplam_grup} arası bir sayı girin): "))

        if grup_sayisi > 0 and grup_sayisi <= toplam_grup:
            baslangic_index = (grup_sayisi - 1) * 50
            secilen_50lik_grup = kelimeler[baslangic_index:baslangic_index + 50]
            print(f"Seçilen 50'lik satır grubu ({grup_sayisi}. grup):")
            for kelime in secilen_50lik_grup:
                print(kelime)

            print(f"Son gösterilen grup: {grup_sayisi}.")

        else:
            print(f"Lütfen 1 ile {toplam_grup} arasında bir sayı girin.")

    except ValueError:
        print("Lütfen geçerli bir sayı giriniz.")
    except Exception as e:
        print(f"Bir hata oluştu: {e}")

